---
services:
  opentakserver-ui:
    image: opentakserver-ui:latest
    build:
      context: .
      tags:
        - opentakserver-ui:${OTSUI_VERSION}
        - opentakserver-ui:latest
    container_name: opentakserver-ui
    environment:
      OTSUI_VERSION: ${OTSUI_VERSION}
