---
services:
  opentakserver-ui:
    image: opentakserver-ui:latest
    build:
      context: .
      args:
        - BUILD_VERSION=${BUILD_VERSION}
      tags:
        - opentakserver-ui:${BUILD_VERSION}
        - opentakserver-ui:latest
    container_name: opentakserver-ui
